### ISSUE TITLE
got 1 primary alignment(s). Input is not paired or not qname-grouped?

### ISSUE THREAD

**Issue by xiekunwhy** [delocalizer/streammd#37]
Hi,

I got this error when running streammd 4.0.2,
[2023-01-07 21:40:43.242] [main] [info] BloomFilter initialized with p=1e-06 n=993917924 m=34359738368 k=10
[2023-01-07 21:40:43.242] [main] [info] BloomFilter capacity: 993917924 items
[2023-01-07 21:40:43.993] [main] [error] A00601:371:HLNYMDSXY:3:1101:3983:19413: got 1 primary alignment(s). Input is not paired or not qname-grouped?

The pipeline I used (for huge sequencing data),
step 1
split fastq into many pieces,
step 2
bwa mem map each pieces seperately,
step 3
samtools sort each pieces seperately,
step 4
samtools merge pieces into a single bam
step 5
samtools-1.9 view -\@ 4 -h F1.sort.bam|streammd --metrics F1.dedup.metrics |samtools-1.9 view -\@ 4 -bS -o F1.dedup.bam

And got the error I have mentioned above.

Best,
Kun

**Comment by delocalizer** [comment]
streammd operates on QNAME-grouped SAM records only, so the sorting needs to happen after the duplicate marking. As a sketch, your pipeline needs to look something like:
1. split fastqs
2. bwa mem map the fastq pieces
3. `samtools merge -n -O SAM -o -  [1.bam] [2.bam] ... | streammd |samtools sort ...`

**Comment by xiekunwhy** [comment]
When data size is very large (bam size ~1T), samtools sort may give errors (maybe tmp files number is too large), so sort each pieces seperately and merge sorted files is the best way. And I need to use samtools markdup if streammd can not accept position sorted sam.

**Comment by delocalizer** [comment]
I think this is now a discussion about pipeline engineering rather than an issue with streammd _per se_. As noted in the documentation, streammd only operates on QNAME-grouped input stream; that's the tradeoff for the small memory footprint. Having said that, samtools sort can easily handle a 1T bam. If you're running into errors with number of temp files it could be that you've hit a system `nofiles` value that you can alter with `ulimit`. And/or you can increase the temp file size with `-m` option. But again, that's a discussion about samtools usage that's out of scope here.
